name: compilar el paquete

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: inicializar python v${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: instalar las dependencias
      run: |
        python -m pip install --upgrade pip build
        python -m pip install flake8 mypy pytest pygame
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: comprobar la calidad del código
      run: |
        flake8 --extend-ignore F401 .
        mypy .
    - name: compilar el paquete
      run: |
        python -m build
